// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAloCKUt_sDUnRJsQnQ8YHBDxBeQyjJDkg',
    appId: '1:913273396224:web:f4a59f5aab39b4fefc4ce5',
    messagingSenderId: '913273396224',
    projectId: 'nutrisee-1770e',
    authDomain: 'nutrisee-1770e.firebaseapp.com',
    storageBucket: 'nutrisee-1770e.firebasestorage.app',
    measurementId: 'G-Z8J4VCTLHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1f9DEZ0OJN3V_EpV7cyRb2SiaTZ1j0z0',
    appId: '1:913273396224:android:f9bc334e2adad6c3fc4ce5',
    messagingSenderId: '913273396224',
    projectId: 'nutrisee-1770e',
    storageBucket: 'nutrisee-1770e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAloCKUt_sDUnRJsQnQ8YHBDxBeQyjJDkg',
    appId: '1:913273396224:web:537bb74e65199457fc4ce5',
    messagingSenderId: '913273396224',
    projectId: 'nutrisee-1770e',
    authDomain: 'nutrisee-1770e.firebaseapp.com',
    storageBucket: 'nutrisee-1770e.firebasestorage.app',
    measurementId: 'G-QTG4Z6DHR8',
  );
}
